### ISSUE TITLE
How to add a new language?

### ISSUE THREAD

**Issue by Mo7mud** [Separius/AgahKeyboard#1]
Hi,
How to add a new language or all languages?

**Comment by Separius** [comment]
- use [this](https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/ics-plus-aosp/tools/makedict/) to create a dictionary (or use AOSP's provided ones)

- add the subtype to xml/method.xml and KeyboardTextTable.java

- add your rows and keyboard the the xml resources

**Comment by Mo7mud** [comment]
Hi, 
Where can I find AOSP's provided dictionaries?

Is there any step by step tutorial for this process?

**Comment by Separius** [comment]
[provided dictionaries](https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/master/dictionaries/)

For the step by step part, you can look at LatinIME and easily figure out the process

**Comment by Mo7mud** [comment]
Thank you very much

Unfortunately the list doesn't contain Arabic dictionary, is there any way to get other languages not included in provided dictionaries?

**Comment by Separius** [comment]
[This](https://forum.xda-developers.com/showthread.php?t=1027207) might help you

If that didn't work, try to read the code, and also open the provided word_lists, the format is easy to understand.

**Comment by Mo7mud** [comment]
Hi,
Sorry for late reply.
The format is easy to understand but writing all my language's vocabulary isn't.
This is the problem for me.

I found this[ project](https://github.com/sergeychilingaryan/AOSP-Kayboard-7.1.2) but I can't run it
Can you help me with it?

**Comment by Separius** [comment]
Unfortunately I am really busy right now so I can't promise to help you but I'll try my best to find a time and check that project.

**Comment by Mo7mud** [comment]
Thank you
I'm writing this comment using your awesome keyboard using gestures.
I did all 3 steps but my language doesn't show in languages selection page
What may be the problem?

**Comment by Mo7mud** [comment]
Finally I got it to work
But how can I make it to store new words in the dictionary automatically?
And how to add long press feature which available in the original AOSP keyboard?
